imports:
    txn-examples: t/data/

git module txn-examples:
    url: git://github.com/atweiden/txn-examples.git
    rev: 24e6afb09314559d3c686e137e429f681ddcb024
    drop:
        - README.md
        - UNLICENSE
        - .gitignore
        - .hgignore
        - "*.sh"
