imports:
    txn-examples: t/data/

git module txn-examples:
    url: git://github.com/atweiden/txn-examples.git
    rev: ff3b16b206267b312ddd44ef6e3710917b5e9999
    drop:
        - README.md
        - UNLICENSE
        - .gitignore
        - .hgignore
        - "*.sh"
