branches:
    only:
        - master

language: perl6

perl6:
    - latest

# sudo required for libxxhash installation
sudo: required

env:
    - PATH=~/.rakudobrew/bin:~/.rakudobrew/moar-nom/install/share/perl6/site/bin:~/.rakudobrew/moar-nom/zef/bin:$PATH

before_install:
    # install libxxhash into /usr/lib/libxxhash.so
    - curl https://codeload.github.com/Cyan4973/{xxHash}/{tar.gz}/{v0.6.2} -o "#1-#3.#2"
    - tar xvzf xxHash-v0.6.2.tar.gz
    - cd xxHash-0.6.2
    - mkdir build && pushd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr ../cmake_unofficial/
    - make all
    - popd
    - sudo make install -C build/
    - cd $TRAVIS_BUILD_DIR
    # get t/data
    - git clone https://github.com/atweiden/txn-examples t/data
    - cd t/data
    - git checkout ff3b16b206267b312ddd44ef6e3710917b5e9999

install:
    - cd $TRAVIS_BUILD_DIR
    - rakudobrew build zef
    - zef --deps-only --/test install .
